M48
; DRILL file KiCad 10.0.5 date 2026-08-13T17:58:49
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-13T17:58:49+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X116.11Y-147.6
X121.89Y-147.6
T2
X114.0Y-72.0
X155.0Y-130.0
X160.0Y-74.0
M30
